from google.adk.agents.llm_agent import LlmAgent
from google.adk.agents.sequential_agent import SequentialAgent
from . import config

# --- 1. Define Sub-Agents for Each Pipeline Stage ---

# Code Writer Agent
# Takes the initial specification (from user query) and writes code.
code_writer_agent = LlmAgent(
    name="CodeWriterAgent",
    model=config.MODEL_NAME,
    instruction="""You are a Python Code Generator.
Based *only* on the user's request, write Python code that fulfills the requirement.
Output *only* the complete Python code block, enclosed in triple backticks (```python ... ```). 
Do not add any other text before or after the code block.
""",
    description="Writes initial Python code based on a specification.",
    output_key="generated_code" # Stores output in state['generated_code']
)

# Code Reviewer Agent
# Takes the code generated by the previous agent (read from state) and provides feedback.
code_reviewer_agent = LlmAgent(
    name="CodeReviewerAgent",
    model=config.MODEL_NAME,
    instruction="""You are an expert Python Code Reviewer. 
    Your task is to provide constructive feedback on the provided code.

    **Code to Review:**
    ```python
    {generated_code}
    ```

**Review Criteria:**
1.  **Correctness:** Does the code work as intended? Are there logic errors?
2.  **Readability:** Is the code clear and easy to understand? Follows PEP 8 style guidelines?
3.  **Efficiency:** Is the code reasonably efficient? Any obvious performance bottlenecks?
4.  **Edge Cases:** Does the code handle potential edge cases or invalid inputs gracefully?
5.  **Best Practices:** Does the code follow common Python best practices?

**Output:**
Provide your feedback as a concise, bulleted list. Focus on the most important points for improvement.
If the code is excellent and requires no changes, simply state: "No major issues found."
Output *only* the review comments or the "No major issues" statement.
""",
    description="Reviews code and provides feedback.",
    output_key="review_comments", # Stores output in state['review_comments']
)


# Code Refactorer Agent
# Takes the original code and the review comments (read from state) and refactors the code.
code_refactorer_agent = LlmAgent(
    name="CodeRefactorerAgent",
    model=config.MODEL_NAME,
    instruction="""You are a Python Code Refactoring AI.
Your goal is to improve the given Python code based on the provided review comments.

  **Original Code:**
  ```python
  {generated_code}
  ```

  **Review Comments:**
  {review_comments}

**Task:**
Carefully apply the suggestions from the review comments to refactor the original code.
If the review comments state "No major issues found," return the original code unchanged.
Ensure the final code is complete, functional, and includes necessary imports and docstrings.

**Output:**
Output *only* the final, refactored Python code block, enclosed in triple backticks (```python ... ```). 
Do not add any other text before or after the code block.
""",
    description="Refactors code based on review comments.",
    output_key="refactored_code", # Stores output in state['refactored_code']
)


# --- 2. Create the SequentialAgent ---
# This agent orchestrates the pipeline by running the sub_agents in order.
code_pipeline_agent = SequentialAgent(
    name="CodePipelineAgent",
    sub_agents=[code_writer_agent, code_reviewer_agent, code_refactorer_agent],
    description="Executes a sequence of code writing, reviewing, and refactoring.",
    # The agents will run in the order provided: Writer -> Reviewer -> Refactorer
)

# --- 3. Define Tool to Run the Pipeline ---
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
import asyncio

async def run_coding_pipeline(task: str) -> str:
    """Runs the code development pipeline for a given coding task.
    
    Args:
        task: The coding task description.
        
    Returns:
        The final refactored code.
    """
    print(f"\n[Tool] Starting coding pipeline for: {task}")
    
    session_service = InMemorySessionService()
    import uuid
    pipeline_session_id = str(uuid.uuid4())
    
    # Create session (async)
    await session_service.create_session(
        app_name=config.APP_NAME, 
        user_id="pipeline_user", 
        session_id=pipeline_session_id
    )
    
    runner = Runner(
        agent=code_pipeline_agent, 
        app_name=config.APP_NAME, 
        session_service=session_service
    )
    
    content = types.Content(role='user', parts=[types.Part(text=task)])
    
    # Runner.run is blocking, so we run it in a separate thread to not block the async tool execution
    def _run_sync():
        return list(runner.run(
            user_id="pipeline_user", 
            session_id=pipeline_session_id, 
            new_message=content
        ))
    
    loop = asyncio.get_running_loop()
    events = await loop.run_in_executor(None, _run_sync)
    
    final_code = "No code generated."
    for event in events:
        if event.is_final_response() and event.content:
            final_code = event.content.parts[0].text.strip()
            
    return final_code

# --- 4. Define General Agent ---
general_agent = LlmAgent(
    name="GeneralAgent",
    model=config.MODEL_NAME,
    instruction="""You are a helpful AI assistant.
If the user asks you to write code, develop a program, or script something, you MUST use the `run_coding_pipeline` tool.
For all other queries (like "how are you", "what is the weather", general knowledge), answer directly without using the tool.
""",
    tools=[run_coding_pipeline],
    description="A general assistant that delegates coding tasks to a pipeline."
)

# For ADK tools compatibility, the root agent must be named `root_agent`
root_agent = general_agent
